### ISSUE TITLE
ic-ajax no longer honors OVERRIDE_REST_ADAPTER

### ISSUE THREAD

**Issue by kenelliott** [instructure/ic-ajax#15]
With commit be1ad8f6a363c9a299258961610b8b94babf572e ic-ajax does not honor the OVERRIDE_REST_ADAPTER setting. Below are some jsfiddles demonstrating the behavior.

With latest commit and OVERRIDE_REST_ADAPTER = false the response in console shows jqXHR.
http://jsfiddle.net/webguy/qD4V3/2/

With the previous commit and OVERRIDE_REST_ADAPTER = false the response in console is unaffected.
http://jsfiddle.net/webguy/qD4V3/3/

And finally a jsfiddle without ic-ajax included.
http://jsfiddle.net/webguy/qD4V3/4/

**Comment by fivetanley** [comment]
should be fixed in 1.0.4. sorry for breaking things today. :(
