### ISSUE TITLE
Syntax error on loading main.js

### ISSUE THREAD

**Issue by asurabhi** [instructure/ic-ajax#16]
Hi
I am getting following error, when i try to use your library.
Uncaught SyntaxError: <unknown message reserved_word> at ... ic-ajax/lib/main.js:9
Using chromer latest version.
Let me know if you need any information.

-Ashwin

**Comment by nathanhammond** [comment]
You can only use the "main.js" version if you're leveraging something like https://github.com/square/es6-module-transpiler. If you're not using something like that you should use the appropriate version from the `dist` folder (which is where the pre-built versions live).

@fivetanley @rpflorence This issue can be closed.
