### ISSUE TITLE
defineFixture based on request type

### ISSUE THREAD

**Issue by hyderali** [instructure/ic-ajax#18]
There isn't a way to define fixtures based on request type. 
Say in success handler of the POST request of a url, GET request of the same url is called, there isn't a hook to define the fixture for the GET request, and the fixture for the POST request will be returned which is not correct.

Here is a [jsbin](http://emberjs.jsbin.com/tinih/6/edit) with the above said requirement.

The following is the route structure.

``` javascript
this.resource('posts',function(){
    this.route('new');
    this.resource('posts.list',function(){
      this.route('details',{path: '/:post_id'});
    });
  });
```

There will be a transition from the `posts.new` route, to the `posts.list.details` route, when the `save` action is called in the new route.

``` javascript
App.PostsNewRoute = Ember.Route.extend({
  actions: {
    save: function() {
      var self = this;
      ic.ajax.raw({url: '/posts',type: 'POST'}).then(function(response){
        self.transitionTo('posts.list.details',response.post.post_id);
      });
    }
  }
});
```

The fixture for the POST request can be defined before calling the save action.  
But the fixture for the GET request can't be defined as calling the save action will transition to the `posts.list`route, and there is no hook to define the fixture before the transition.

One possible solution will be to define fixtures in a two dimensional array, `__fixtures__[url][type]`.

**Comment by ryanflorence** [comment]
Thanks for the issue.

The fixture feature isn't designed to be robust, its just for quick prototyping and testing simple use-cases.

For more involved use-cases like yours I'd use a library designed specifically for mocking a server, like pretender https://github.com/trek/pretender.

**Comment by hyderali** [comment]
@rpflorence Thank you for the suggestion.
