### ISSUE TITLE
Problems with Ember-Data

### ISSUE THREAD

**Issue by Emerson** [instructure/ic-ajax#21]
I'm no expect in Ember or ic-ajax, but I wanted to point out something that caused me a great amount of distress.

While building an Ember app with Ember-CLI _(and Ember-Data)_, I came across a problem with ic-ajax that I cannot fully understand. At some point [ic-ajax reopens the RESTAdapter](https://github.com/instructure/ic-ajax/blob/802a2edc9d3243e8907e134c193bdbd19e1ea1fb/dist/amd/main.js#L135) and overrides the ajax method. This monkey patch took me a really long time to track down and causes some issues with Ember-Data that I do not fully understand.

In my situation, it seemed like ic-ajax did not handle the error states in the same way the RESTAdapter is supposed to. Specifically, when my server returned a `422` with a well formed hash of errors, ic-ajax failed to trigger Ember-Data properly and the record was never put into an invalid state, nor was the DS.InvalidError object properly populated.

I fixed the problem by re-monkeypatching the RESTAdapter to it's original state, but wanted to flag this issue so that it can be properly investigated.

It's possible this problem is isolated to me but I thought I would raise this issue just in case other people were finding the same problem.

**Comment by ryanflorence** [comment]
i just saw this in our app, I still don't know why anybody wants ic-ajax to own the ajax method in ember-data. @fivetanley what's the point? I'd like to remove it.

**Comment by fivetanley** [comment]
it was just so you don't have to wire it up manually, we should remove it

**Comment by fivetanley** [comment]
closed by 58bd96d19619348005afe3749d47fc96f773e8e6

**Comment by fishermand46** [comment]
So, how are you supposed to use ic-ajax in tests now? Should you do this re-wiring on a per-test basis? Or override the ApplicationAdapter in the test setup?

p.s. I know this isn't a support forum, but I haven't been able to find in-depth documentation on testing with ic-ajax.

http://guides.emberjs.com/v1.10.0/testing/testing-xhr/
