### ISSUE TITLE
consider renaming to mc-ajax

### ISSUE THREAD

**Issue by stefanpenner** [instructure/ic-ajax#25]
because well..
![screenshot 2014-09-05 07 59 53](https://cloud.githubusercontent.com/assets/1377/4166685/56d8f77e-350d-11e4-997c-d541c1fd7ac2.png)

**Comment by machty** [comment]
:+1:

**Comment by ryanflorence** [comment]
good point, refresh and check the url.

**Comment by machty** [comment]
uhhhhhhhh

**Comment by machty** [comment]
please to revert?
