### ISSUE TITLE
offer

### ISSUE THREAD

**Issue by stefanpenner** [instructure/ic-ajax#32]
Hello friends of instructor, I would like to offer myself as an active maintainer of this project.

I would like to get the tests passing again, and have some ideas for a 3.x release.

let me know

**Comment by coderberry** [comment]
:+1:

**Comment by knomedia** [comment]
:+1:

**Comment by ryanflorence** [comment]
@stefanpenner and I talked and he's going to just fork or simply copy/paste the code he wants from ic-ajax and make a new thing. No emotions here about the `ic-` legacy.

@stefanpenner as soon as you have something, can you open an issue here and we'll put it in the readme that this is no longer under development and to use your new thing?

**Comment by toranb** [comment]
@stefanpenner thanks for offering to maintain this library! Looking forward to the new library/addon !
