### ISSUE TITLE
Add #json(url, options)

### ISSUE THREAD

**Issue by knownasilya** [instructure/ic-ajax#33]
Would be nice to have this shortcut:

``` js
icAjax.json('/api/users/1', {
  type: 'put',
  data: {
   // user data
  }
})
.then(function (data) {
  //..
});
```

By default the following options are used:

```
dataType: 'json',                                                                            
contentType: 'application/json; charset=UTF-8',
type: 'get'
```

and `JSON.stringify(..)` is called on `data`.

**Comment by stefanpenner** [comment]
:+1:

**Comment by kellyselden** [comment]
@ryanflorence @fivetanley @stefanpenner I would be interesting in adding this. Would it be merged, or is this project deprecated in favor of fetch?

**Comment by stefanpenner** [comment]
> Would it be merged, or is this project deprecated in favor of fetch?

in-favor of ember-ajax
