### ISSUE TITLE
Using request blocks web font loading?

### ISSUE THREAD

**Issue by devinus** [instructure/ic-ajax#41]
This happens on both Firefox and Chrome. Using a lot of `request` calls in `setupController` will make loading web fonts loaded in the `<head>` happen really late.

**Comment by devinus** [comment]
<img width="686" alt="screen shot 2015-07-25 at 7 59 44 am" src="https://cloud.githubusercontent.com/assets/4836/8889536/855acd4a-32a3-11e5-872e-f60ca9ac9b1a.png">

Notice how the AJAX calls before e.g. font loading and image loading, but it will make the font loading slower when it should be first-come, shouldn't it?

**Comment by stefanpenner** [comment]
> Notice how the AJAX calls before e.g. font loading and image loading, but it will make the font loading slower when it should be first-come, shouldn't it?

FYI: you actually left out the timings, so i cannot come to the same conclusion as you.

**Comment by devinus** [comment]
@stefanpenner Why would the timings matter if it's async? AJAX requests should NOT make other things load slower, right?

**Comment by stefanpenner** [comment]
> @stefanpenner Why would the timings matter if it's async? AJAX requests should NOT make other things load slower, right?

Yes, but i would love to see them. I feel like i am only being shown a list of files, that don't indicate the problem. My curiosity is getting the better of me, but now i feel like i dont have all the information.

**Comment by stefanpenner** [comment]
If you can provide a demo somewhere, it would be much easier to diagnose, rather then in the abstract.

I am doubltful that this is an ic-ajax problem, but am willing to investigate assuming i am provided some good starting point for diagnosis.

**Comment by devinus** [comment]
Here it is with timings:

<img width="1440" alt="screen shot 2015-07-25 at 8 51 05 am" src="https://cloud.githubusercontent.com/assets/4836/8889687/558f5138-32aa-11e5-83a1-81a661138b71.png">

**Comment by devinus** [comment]
@stefanpenner Ok, this is **REALLY** weird. If I add a `loading` substate to this route, it doesn't happen.

**Comment by devinus** [comment]
With a loading substate:

<img width="1440" alt="screen shot 2015-07-25 at 8 55 00 am" src="https://cloud.githubusercontent.com/assets/4836/8889700/de0d1202-32aa-11e5-99d9-0f6369c6c1f2.png">

**Comment by stefanpenner** [comment]
Ah, you have hit the max number of active connections to anyone host (which is 6 in chrome).

You likely just want to be sure the image requests and fonts happen earlier, or move static assets to a different host (cdn, assets.domain.com) as it would get a new limit of 6 connections.

**Comment by devinus** [comment]
This is interesting. So because 6 is the limit, it is cycling through all the fired off requests in batches of 6 before finally getting to my webfonts which unfortunately don't fire until they're parsed in the page.

**Comment by stefanpenner** [comment]
yup this is how the browser works. You'll have to re-order or split across multiple hosts.
